zhuangxiusheji/zhuangxiusheji/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from zx_user.views import index
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('zx_user.urls',namespace='user')),
    url(r'^user_center/', include('zx_user_center.urls', namespace='user_center')),
    url(r'^anli/', include('zx_anli.urls', namespace='anli')),
    url(r'^draw/', include('zx_draw.urls', namespace='draw')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zhuangxiusheji/zx_anli/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^showCompanies/$', views.show_company, name='showCompanies'),
    url(r'^show_detail/$', views.show_detail, name='show_detail'),
    url(r'^give_case/$', views.give_case, name='give_case'),
    url(r'^case_handel$', views.case_handel, name='case_handel'),
    url(r'^check_case/$', views.check_case, name='check_case'),
    url(r'^user_case/$', views.user_case, name='user_case'),
    url(r'^company_case/$', views.company_case, name='company_case'),
    url(r'^company_suggestion/$', views.company_suggestion, name='company_suggestion'),
    url(r'^suggestion_handel/$', views.suggestion_handel, name='suggestion_handel'),
    url(r'^write_comment/$', views.write_comment, name='write_comment'),
    url(r'^comment_handel/$', views.comment_handel, name='comment_handel'),
]

zhuangxiusheji/zx_draw/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^image/$', views.loadImage, name='image'),
    url(r'^upload_image/', views.upload_image, name='upload_image'),
]

zhuangxiusheji/zx_user/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^index_for_user/$', views.index_for_user, name='index_for_user'),
    url(r'^index_for_company/$', views.index_for_comapny, name='index_for_company'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^login/$', views.login, name='login'),
    url(r'^select/$', views.select_kind, name='select'),
    url(r'^kind_handel/$', views.kind_handel, name='kind_handel'),
    url(r'^register/$', views.register, name='register'),
    url(r'^longin_handel/$', views.login_handel, name='longin_handel'),
    url(r'^register_handel_forOrd/$', views.register_handel_forOrd, name='register_handel_forOrd'),
    url(r'^register_handel_forCom/$', views.register_handel_forCom, name='register_handel_forCom'),
    url(r'^del_session/$', views.del_session, name='del_session'),
    url(r'^verifycode$', views.verifycode, name='verifycode'),
    url(r'^aboutUs/$', views.aboutUs, name='aboutUs'),
]

zhuangxiusheji/zx_user_center/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^show/$', views.user_center, name='show'),
    url(r'^personal/$', views.personal, name='personal'),
    url(r'^modify_personal$', views.modify_personal, name='modify_personal'),
    url(r'^modify_personal_handel$', views.modify_personal_handel, name='modify_personal_handel'),
    url(r'^show_for_company/$', views.user_center_company, name='show_for_company'),
    url(r'^corporate/$', views.corporate, name='corporate'),
    url(r'^modify_company/$', views.modify_company, name='modify_company'),
    url(r'^modify_company_handel/$', views.modify_company_handel, name='modify_company_handel')
]

zhuangxiusheji/zx_anli/models.py
from django.db import models
from zx_user.models import Ordinary_User, Company_User

class AnliManager(models.Manager):

    def create(self, index):
        new = Anli()
        new.company = index['companyid']
        new.anli_name = index['name']
        new.anli_describe = index['text']
        new.ordinary_user = index['user']
        new.area = index['area']
        new.case_style = index['case_style']
        new.huxing = index['huxing']
        new.save()
        return new

# 用户提交的案例类
class Anli(models.Model):

    anli_name = models.CharField(max_length=30)
    ordinary_user = models.ForeignKey(Ordinary_User) # 外键是普通用户
    anli_describe = models.TextField(max_length=2000)
    company = models.IntegerField(default=0)
    answer = models.BooleanField(default=False)
    score = models.IntegerField(default=0)

    area = models.CharField(max_length=30, choices=(('0-100','100平米以下'), ('100+', '100平米以上') ))
    case_style = models.CharField(max_length=30, choices=(('O','欧美风格'),('D','东方风格')) )
    huxing = models.CharField(max_length=30, choices=(('1','一室一厅'), ('2','两室两厅'),('3', '三室两厅'),('4','其他')) )
    cases = AnliManager()

    def __str__(self):
        return self.anli_name

    class Meta:
        db_table = 'anli'

# 评论类
class Comments(models.Model):
    # 用户发表的评论
    comment = models.TextField(max_length=2000)
    # 外键是评论的案例
    anli = models.ForeignKey(Anli)

    class Meta:
        db_table = 'commments'

# 公司对案例的意见类
class Suggestions(models.Model):

    suggestion = models.TextField(max_length=2000)
    anli = models.ForeignKey(Anli)
    company = models.ForeignKey(Company_User)

    class Meta:
        db_table = 'suggestions'

class CaseImage(models.Model):
    case = models.ForeignKey(Anli)
    image = models.ImageField(upload_to='anli_images/', null=False, blank=True)
    imageName = models.CharField(max_length=20, default='')
    class Meta:
        db_table = 'images'

zhuangxiusheji/zx_anli/views.py
from django.shortcuts import render, redirect
from zx_user.models import Company_User, Ordinary_User, CompanyImage
from .models import Anli, CaseImage, Suggestions, Comments

def show_company(request):
    companies = Company_User.comanyUsers.get_queryset()
    uid = request.session.get('uid', default=None)
    user_kind = request.session.get('user_kind', default=0)
    uname = ''
    if user_kind == 'ordinary_user':
        uname = Ordinary_User.users.get(id=uid)
    print(companies)

    if request.method == 'POST':
        post = request.POST
        price = post.get('price')
        style = post.get('style')
        companies = Company_User.comanyUsers.filter(paice_range=price, style=style)
        pass
    comtext = {
        'companies':companies,
        'uname':uname,
    }
    return render(request, 'showCompanies.html', comtext)

def show_detail(request):
    uid = request.GET['id']
    company = Company_User.comanyUsers.get(id=uid)
    companyImages = company.companyimage_set.all()
    context = {
        'company':uid,
        'name':company.company_name,
        'companyNum':company.company_num,
        'mail':company.account_mail,
        'examine':company.examine,
        'index':company.account_describe,
    }
    i = 1
    for image in companyImages:
        context['image' + str(i)] = image.image.url
        i += 1
    return render(request, 'show_detail.html', context)

def give_case(request):
    # 基本用户给公司提交案例
    uid = request.POST['companyid']
    context = {
        'company':uid
    }
    return render(request, 'writeCase.html', context)

def case_handel(request):

    uid = request.session.get('uid', default=None)
    post = request.POST
    case_name = post.get('case_name')
    companyid = post.get('companyid')
    case_text = post.get('case_text')
    area = post.get('area')
    case_style = post.get('case_style')
    huxing = post.get('huxing')
    user = Ordinary_User.users.get(id=uid)
    index = {
        'name': case_name,
        'companyid': companyid,
        'text': case_text,
        'user': user,
        'area':area,
        'case_style':case_style,
        'huxing':huxing,
    }
    newCase = Anli.cases.create(index)

    # 存储图片
    file01 = request.FILES.get('case_image01', default='')
    file02 = request.FILES.get('case_image02', default='')
    file03 = request.FILES.get('case_image03', default='')
    images = [file01, file02, file03]
    for image in images:
        if image != '':
            caseImage = CaseImage(image=image, case=newCase)
            caseImage.save()

    return redirect('/anli/showCompanies')

def check_case(request):
    # 查看用户案例  通过get方法得到id
    cid = request.GET['cid']
    case = Anli.cases.get(id=cid)
    caseName = case.anli_name
    caseImages = case.caseimage_set.all()
    caseText = case.anli_describe
    suggestion = case.suggestions_set.all()
    suggNum = len(suggestion)
    comments = case.comments_set.all()
    commNum = len(comments)
    # image = getImage(caseImage)
    context = {
        'caseName':caseName,
        'caseImage':caseImages,
        'caseText':caseText,
        'suggestion':suggestion,
        'suggNum':suggNum,
        'comments':comments,
        'commNum':commNum,
        'cid':cid,
    }
    return render(request, 'showCase.html', context)

def write_comment(request):
    # 写评论的请求
    post = request.POST
    cid = post.get('cid')
    context = {
        'cid':cid
    }
    return render(request, 'writeComment.html', context)

def comment_handel(request):
    # 产生新评论
    post = request.POST
    text = post.get('comment_text')
    cid = post.get('cid')
    case = Anli.cases.get(id=cid)
    comment = Comments(comment=text, anli=case)
    comment.save()
    return redirect('/anli/user_case/')

def getImage(image):
    from PIL import Image
    from io import BytesIO
    buf = BytesIO()
    # buf = image
    im = Image.fromstring(image)
    im.save(buf, 'png')

def user_case(request):
    # 展示案例
    cases = Anli.cases.all()
    if request.method == 'POST':
        post = request.POST
        area = post.get('area')
        case_style = post.get('case_style')
        huxing = post.get('huxing')
        cases = Anli.cases.filter(area=area, case_style=case_style, huxing=huxing)
    context = {
        'cases':cases,
    }
    return render(request, 'userCase.html', context)

def company_case(request):
    # 公司查看案例
    uid = request.session.get('uid', default=None)
    user_kind = request.session.get('user_kind', default=None)

    if user_kind == 'company_user':
        cases = Anli.cases.filter(company=uid)
        print(cases, type(cases))
        context = {
            'cases':cases,
        }
        return render(request, 'companyCase.html', context)

def company_suggestion(request):
    # 公司用户对案例提交反馈意见
    cid = request.GET['cid']
    case = Anli.cases.get(id=cid)
    caseName = case.anli_name
    caseImages = case.caseimage_set.all()
    caseText = case.anli_describe
    answer = case.answer
    sugg = ''
    if answer == False:
        sugg = ''
    elif answer == True:
        suggestion = Suggestions.objects.get(anli_id=case)
        sugg = suggestion.suggestion
        print(sugg)
    context = {
        'caseName': caseName,
        'caseImage': caseImages,
        'caseText': caseText,
        'sugg': sugg,
        'answer':answer,
        'cid':cid,
    }

    return render(request, 'submitSuggestion.html', context)

def suggestion_handel(request):
    # 创建新意见
    post = request.POST
    text = post.get('suggestion')
    cid = post.get('cid')
    uid = request.session.get('uid', default=None)
    com = Company_User.comanyUsers.get(id=uid)
    case = Anli.cases.get(id=cid)
    sugg = Suggestions(suggestion=text, anli=case, company=com)
    sugg.save()
    case.answer = True
    case.save()
    # /user_center/corporate/
    return redirect('/anli/company_case/')

zhuangxiusheji/zx_anli/templates/companyCase.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block title %}
    <title>用户案例</title>
{% endblock title %}
{% block style %}
    <style>

</style>
{% endblock %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						    <li><a href="{% url 'user:index_for_company' %}" >主页</a></li>
                            <li><a href="{% url 'user_center:show_for_company' %}" class="active">案例中心</a></li>
                            <li><a href="{% url 'user_center:corporate' %}">公司资料</a></li>
                            <li><a href="{% url 'draw:image' %}">在线绘图</a></li>
                            <li><a href="{% url 'user:del_session' %}">退出登录</a></li>
							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>
			</div>
		</div>
{% endblock header %}
{% block body %}
	<div class="container">
	<div class="gallery">
		<h3>用户案例</h3>
    <table width="1000" style="height: 100px;">
	<thead>
		<th><tr>
		<td>案例名</td>
		<td>用户名</td>
		<td>评论数</td>
		</tr></th>

	</thead>
	 <tbody>
     {% for case in cases %}
        <tr>
		<td><a href="{% url 'anli:company_suggestion' %}?cid={{ case.id }}">{{ case.anli_name }}</a></td>
		<td>{{ case.ordinary_user.account_number }}</td>
		<td></td>
		</tr>
     {% endfor %}
	</tbody>
</table>
	<!--script-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
			<script type="text/javascript" src="{% static 'js/nivo-lightbox.min.js'%}"></script>
				<script type="text/javascript">
				$(document).ready(function(){
				    $('#nivo-lightbox-demo a').nivoLightbox({ effect: 'fade' });
				});
				</script>

			<!---->
    </div>
</div>
{% endblock body %}

zhuangxiusheji/zx_anli/templates/showCase.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						    <li><a href="{% url 'user:index_for_user' %}" >主页</a></li>
                            <li><a href="{% url 'user_center:show' %}" class="active">案例中心</a></li>
                            <li><a href="{% url 'user_center:personal' %}">个人资料</a></li>
                            <li><a href="{% url 'draw:image' %}">在线绘图</a></li>
                            <li><a href="{% url 'user:del_session' %}">退出登录</a></li>
							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>

{% block content %}
<div class="fir" align="center" style="padding: 60px">

    <div class="sec" style="padding:30px;">
        <p align="center" style="margin-bottom:60px;width:620px;color: red">
            {{ caseName }}
        </p>
        <h3 align="left" style="color: whitesmoke; padding: 30px">案例图片：</h3>
        {% for image in caseImage %}
            <img src="{{ image.image.url }}" width="350px">
        {% endfor %}
        <h3 align="left" style="color: whitesmoke; padding: 30px">案例介绍：</h3>
        <p>
            <textarea rows="16" cols="100" name="case_text"  readonly="readonly" style="border-radius:10px; background-color:#222; color:white;resize:none; border: 2px solid #009688;">{{ caseText }}</textarea>
        </p>
        <h3 align="left" style="color: whitesmoke; padding: 30px">得到的回应：</h3>
        {% if suggNum == 0 %}
            <p>
                <textarea rows="16" cols="100" name="case_text"  readonly="readonly" style="border-radius:10px; background-color:#222; color:white;resize:none; border: 2px solid #009688;">暂时为空，请等待公司用户的回应</textarea>
            </p>
        {% endif %}
        {% if suggNum != 0 %}
        <p>
            {% for sugg in suggestion %}
            <textarea rows="16" cols="100" name="case_text"  readonly="readonly" style="border-radius:10px; background-color:#222; color:white;resize:none; border: 2px solid #009688;">{{ sugg.suggestion }}</textarea>
            {% endfor %}
        </p>
        {% endif %}
    </div>
    <div style="border:5px solid #1d2821;width:80%;height:70%;border-radius:10px;padding:20px; color: brown">
        <h3 align="left" style="color: whitesmoke; padding: 30px">用户评论：</h3>
        {% if commNum == 0 %}
            <p style="color: whitesmoke; padding-top: 10px">还没有人评论呢！来坐沙发吧</p>
        {% endif %}
        {% if commNum != 0 %}
            {% for comment in comments %}
                <p style="color: whitesmoke; padding: 30px;align-items: left">{{ comment.comment }}</p>
            {% endfor %}
        {% endif %}
    </div>
    <div style="padding: 30px">
        <form method="post" action="{% url 'anli:write_comment' %}">
            {% csrf_token %}
            <input type="hidden" value="{{ cid }}" name="cid">
            <p><button type="submit" >发送评论</button></p>
        </form>
    </div>


</div>
{% endblock content%}
            </div>
        </div>
{% endblock header %}

zhuangxiusheji/zx_anli/templates/showCase02.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block title %}
    <title>用户案例</title>
{% endblock title %}
{% block style %}
    <style>

</style>
{% endblock %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						    <li><a href="{% url 'user:index_for_user' %}" >主页</a></li>
                            <li><a href="{% url 'user_center:show' %}" class="active">案例中心</a></li>
                            <li><a href="{% url 'user_center:personal' %}">个人资料</a></li>
                            <li><a href="{% url 'draw:image' %}">在线绘图</a></li>
                            <li><a href="{% url 'user:del_session' %}">退出登录</a></li>
							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>
			</div>
		</div>
{% endblock header %}
{% block body %}
	<div class="container">
	<div class="gallery">
		<h3>用户案例</h3>
    <table width="1000" style="height: 100px;">
	<thead>
		<th><tr>
		<td>案例名</td>
		<td>用户名</td>
		<td>评论数</td>
		</tr></th>

	</thead>
	 <tbody>
     {% for case in cases %}
        <tr>
		<td><a href="{% url 'anli:check_case' %}?cid={{ case.id }}">{{ case.anli_name }}</a></td>
		<td>{{ case.ordinary_user.account_number }}</td>
		<td>{{ case.comments_set.count }}</td>
		</tr>
     {% endfor %}
	</tbody>
</table>
	<!--script-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
			<script type="text/javascript" src="{% static 'js/nivo-lightbox.min.js'%}"></script>
				<script type="text/javascript">
				$(document).ready(function(){
				    $('#nivo-lightbox-demo a').nivoLightbox({ effect: 'fade' });
				});
				</script>

			<!---->
    </div>
</div>
{% endblock body %}

zhuangxiusheji/zx_anli/templates/showCompanies.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						<li><a href="{% url 'user:index_for_user' %}" >主页</a></li>
                                     <li><a href="{% url 'user_center:show' %}" class="active">案例中心</a></li>
                                                 <li><a href="{% url 'user_center:personal' %}">个人资料</a></li>
							<li><a href="{% url 'draw:image' %}">在线绘图</a></li>
                            <li><a href="{% url 'user:del_session' %}">退出登录</a></li>
{#												<li><a href="{% url 'user:gallery' %}">装修案例</a></li>#}

							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>
			</div>
		</div>
{% endblock header %}
{% block body %}
    	<div class="container">
	<div class="gallery">
    <div>
    <form method="post" action="{% url 'anli:showCompanies' %}">
        {% csrf_token %}
    选择公司装修的价格区间:
    <select name="price"  >
            <option  value="0-5000">5000元以下</option>
            <option  value="5000-10000">5000到10000元</option>
            <option  value="10000-">10000元以上</option>
    </select>
    &nbsp;&nbsp;&nbsp;&nbsp;选择公司装修的风格:
    <select name="style"  >
            <option  value="O">欧美风</option>
            <option  value="D">东方风</option>
    </select>
       &nbsp;&nbsp;&nbsp; <button type="submit">查询</button>
    </form>
    </div></div></div>
<div align="center" style="padding-bottom:60px;">

<div align="left" style="border:5px solid #1d2821;width:80%;height:70%;border-radius:10px;padding:20px; color: brown">
    <h3 style="margin-top:5px;" align="center">
    这些公司已入驻本网站，点开看看吧！
    </h3>
    <ul>
        {% for company in companies %}
        <li style="margin:10px;"><a href="{% url 'anli:show_detail' %}?id={{ company.id }}" style="font-size: large">{{ company.company_name }}</a></li>
        {% endfor %}
    </ul>
</div>
</div>
{% endblock body %}

zhuangxiusheji/zx_anli/templates/userCase.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block title %}
    <title>用户案例</title>
{% endblock title %}
{% block style %}
    <style>

</style>
{% endblock %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						    <li><a href="{% url 'user:index_for_user' %}" >主页</a></li>
                            <li><a href="{% url 'user_center:show' %}" class="active">案例中心</a></li>
                            <li><a href="{% url 'user_center:personal' %}">个人资料</a></li>
                            <li><a href="{% url 'draw:image' %}">在线绘图</a></li>
                            <li><a href="{% url 'user:del_session' %}">退出登录</a></li>
							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>
			</div>
		</div>
{% endblock header %}
{% block body %}
	<div class="container">
	<div class="gallery">
		<h3>用户案例</h3>
    <div>
        <form method="post" action="{% url 'anli:user_case' %}">
            {% csrf_token %}
        选择空间大小：
        <select name="area">
            <option value="0-100">100平米以下</option>
            <option value="100+">100平米以上</option>
        </select>
        &nbsp;&nbsp;&nbsp;&nbsp;选择装修风格：
        <select name="case_style">
            <option value="O">欧美风格</option>
            <option value="D">东方风格</option>
        </select>
        &nbsp;&nbsp;&nbsp;&nbsp;选择户型：
        <select name="huxing">
            <option value="1">一室一厅</option>
            <option value="2">两室两厅</option>
            <option value="3">三室两厅</option>
            <option value="4">其他</option>
        </select>
            &nbsp;&nbsp;&nbsp;&nbsp;<button type="submit">查询</button>
        </form>
    </div>
    <table width="1000" style="height: 100px;">
	<thead>
		<th><tr>
		<td>案例名</td>
		<td>用户名</td>
		<td>评论数</td>
		</tr></th>

	</thead>
	 <tbody>
     {% for case in cases %}
        <tr>
		<td><a href="{% url 'anli:check_case' %}?cid={{ case.id }}">{{ case.anli_name }}</a></td>
		<td>{{ case.ordinary_user.account_number }}</td>
		<td>{{ case.comments_set.count }}</td>
		</tr>
     {% endfor %}
	</tbody>
</table>
	<!--script-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
			<script type="text/javascript" src="{% static 'js/nivo-lightbox.min.js'%}"></script>
				<script type="text/javascript">
				$(document).ready(function(){
				    $('#nivo-lightbox-demo a').nivoLightbox({ effect: 'fade' });
				});
				</script>

			<!---->
    </div>
</div>
{% endblock body %}