zhuangxiusheji/zhuangxiusheji/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from zx_user.views import index
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('zx_user.urls',namespace='user')),
    url(r'^user_center/', include('zx_user_center.urls', namespace='user_center')),
    url(r'^anli/', include('zx_anli.urls', namespace='anli')),
    url(r'^draw/', include('zx_draw.urls', namespace='draw')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zhuangxiusheji/zx_anli/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^showCompanies/$', views.show_company, name='showCompanies'),
    url(r'^show_detail/$', views.show_detail, name='show_detail'),
    url(r'^give_case/$', views.give_case, name='give_case'),
    url(r'^case_handel$', views.case_handel, name='case_handel'),
    url(r'^check_case/$', views.check_case, name='check_case'),
    url(r'^user_case/$', views.user_case, name='user_case'),
    url(r'^company_case/$', views.company_case, name='company_case'),
    url(r'^company_suggestion/$', views.company_suggestion, name='company_suggestion'),
    url(r'^suggestion_handel/$', views.suggestion_handel, name='suggestion_handel'),
    url(r'^write_comment/$', views.write_comment, name='write_comment'),
    url(r'^comment_handel/$', views.comment_handel, name='comment_handel'),
]

zhuangxiusheji/zx_draw/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^image/$', views.loadImage, name='image'),
    url(r'^upload_image/', views.upload_image, name='upload_image'),
]

zhuangxiusheji/zx_user/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^index_for_user/$', views.index_for_user, name='index_for_user'),
    url(r'^index_for_company/$', views.index_for_comapny, name='index_for_company'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^login/$', views.login, name='login'),
    url(r'^select/$', views.select_kind, name='select'),
    url(r'^kind_handel/$', views.kind_handel, name='kind_handel'),
    url(r'^register/$', views.register, name='register'),
    url(r'^longin_handel/$', views.login_handel, name='longin_handel'),
    url(r'^register_handel_forOrd/$', views.register_handel_forOrd, name='register_handel_forOrd'),
    url(r'^register_handel_forCom/$', views.register_handel_forCom, name='register_handel_forCom'),
    url(r'^del_session/$', views.del_session, name='del_session'),
    url(r'^verifycode$', views.verifycode, name='verifycode'),
    url(r'^aboutUs/$', views.aboutUs, name='aboutUs'),
]

zhuangxiusheji/zx_user_center/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^show/$', views.user_center, name='show'),
    url(r'^personal/$', views.personal, name='personal'),
    url(r'^modify_personal$', views.modify_personal, name='modify_personal'),
    url(r'^modify_personal_handel$', views.modify_personal_handel, name='modify_personal_handel'),
    url(r'^show_for_company/$', views.user_center_company, name='show_for_company'),
    url(r'^corporate/$', views.corporate, name='corporate'),
    url(r'^modify_company/$', views.modify_company, name='modify_company'),
    url(r'^modify_company_handel/$', views.modify_company_handel, name='modify_company_handel')
]

zhuangxiusheji/zx_user/models.py
from django.db import models

class Ordinary_UserManager(models.Manager):

    def create(self, accountnum, password, mail):
        # 写创建对象的方法 创建对象时可以调用该类方法
        ord = Ordinary_User()
        ord.account_number = accountnum
        ord.account_passWord = password
        ord.account_mail = mail
        ord.save()
        return ord

    def if_has(self, uname):
        try:
            self.get(account_number=uname)
        except:
            return False
        return True

    def modify_password(self, uid, newpass, newmail):
        # 修改信息的时候调用该函数
        user = self.filter(id=uid)

        if newmail != '':
            user.update(account_mail = newmail)

        user.update(account_passWord=newpass)
        return True

class Company_UserManager(models.Manager):

    def create(self, accountnum, password, company_name ,mail, company_num, account_describe, style, paice):
        ord = Company_User()
        ord.account_number = accountnum
        ord.company_name = company_name
        ord.account_passWord = password
        ord.account_mail = mail
        ord.account_describe = account_describe
        ord.company_num = company_num
        ord.style = style
        ord.paice_range = paice
        ord.save()
        return ord

    def if_has(self, uname):
        try:
            self.get(account_number=uname)
        except:
            return False
        return True

    def modify_password(self, uid, canshu):
        # 修改信息的时候调用该函数
        user = self.filter(id=uid)
        for key in canshu:
            if canshu[key] != '':
                if key == 'account_passWord':
                    user.update(account_passWord=canshu[key])
                elif key == 'account_mail':
                    user.update(account_mail=canshu[key])
                elif key == 'company_name':
                    user.update(company_name=canshu[key])
                elif key == 'company_num':
                    user.update(company_num=canshu[key])
                elif key == 'account_describe':
                    user.update(account_describe=canshu[key])

        user.update(examine='W')
        user.update(if_passed=False)
        return True


class Ordinary_User(models.Model):
    # 基本用户
    account_number = models.CharField(max_length=20) # 账号
    account_passWord = models.CharField(max_length=40)# 密码
    account_mail = models.CharField(max_length=30)#邮箱
    users = Ordinary_UserManager()

    def __str__(self):
        return self.account_number

    class Meta:
        # 元选项 修改表的名称
        db_table = 'ordinary_user' # 表名
        ordering = ['id'] # 指定查询的排序规则

class Company_User(models.Model):
    # 公司用户
    account_number = models.CharField(max_length=20)  # 账号
    account_passWord = models.CharField(max_length=40)  # 密码
    account_mail = models.CharField(max_length=30)  # 邮箱
    company_name = models.CharField(max_length=20) # 公司名
    company_num = models.CharField(max_length=30) # 营业执照号码
    account_describe = models.TextField(max_length=2000) # 公司描述  审核的依据
    examine = models.CharField(max_length=20, default='W', choices=(('W','审核中'),('Y','审核通过'),('N','未通过'))) # 审核状态
    casefor = models.TextField(max_length=200, default='') # 对该公司的备注
    if_passed = models.BooleanField(default=False) # 审核是否通过
    style = models.CharField(max_length=30, choices=(('O','欧美风格'),('D','东方风格')) )
    paice_range = models.CharField(max_length=30, choices=(('0-5000','5000元以下'), ('5000-10000', '5000到10000元'),('10000-','10000元以上')) )
    comanyUsers = Company_UserManager()

    def __str__(self):
        return self.account_number

    class Meta:
        # 元选项 修改表的名称
        db_table = 'company_user'
        ordering = ['id'] # 指定查询的排序规则

class CompanyImage(models.Model):
    company = models.ForeignKey(Company_User)
    image = models.ImageField(upload_to='company_images/', null=False, blank=True)

    class Meta:
        db_table = 'company_images'

zhuangxiusheji/zx_user/views.py
from django.shortcuts import render, redirect
from django.template import loader, RequestContext
from django.db.models import Max
from django.http import *
from .models import *

def index(request):
    # 主页的请求
    user_kind = request.session.get('user_kind')
    if user_kind == 'ordinary_user':
        return redirect('/user/index_for_user/')
    elif user_kind == 'company_user':
        return redirect('/user/index_for_company/')
    return render(request, 'index.html')

def index_for_user(request):
    # 用户主页的请求
    uid = request.session.get('uid', default=None)
    user = Ordinary_User.users.get(id=uid)
    context = {
        'uname': user.account_number,
    }
    return render(request, 'index_for_user.html', context)

def index_for_comapny(request):
    # 公司主页的请求
    uid = request.session.get('uid', default=None)
    user = Company_User.comanyUsers.get(id=uid)
    context = {
        'uname': user.account_number,
    }
    return render(request, 'index_for_company.html', context)

def gallery(request):
    # 样例演示
    return render(request, 'gallery.html')

def select_kind(request):
    # 注册前选择用户种类
    return render(request, 'select_kind.html')

def kind_handel(request):
    # 根据用户种类返回相应注册页面
    post = request.POST
    user_kind = post.get('user_kind')
    if user_kind == 'ordinary_user':
        return render(request, 'register_for_ordinary.html')
    elif user_kind == 'company_user':
        return render(request, 'register_for_company.html')

def register(request):
    # 普通用户的注册
    buf = verifycode(request)
    image = buf.getvalue()
    context = {
        'image':image,
    }
    return render(request, 'register_for_ordinary.html')

def login(request):
    # 登陆页面的请求
    buf = verifycode(request)
    image = buf.getvalue()
    context = {
        'image':image,
    }
    return render(request, 'login.html', context)

def login_handel(request):
    # 登录会话
    from hashlib import sha1
    post = request.POST
    uname = post.get('uname')
    upwd = post.get('upwd')
    user_kind= post.get('user_kind')
    code = post.get('verifycode')
    verifycode = request.session['verifycode']
    s1 = sha1()
    s1.update(upwd.encode('utf-8'))
    pwd = s1.hexdigest()
    # if code != verifycode:
    #     return HttpResponse('验证码错误')
    if user_kind == 'ordinary_user':
        user = Ordinary_User.users.filter(account_number=uname)
        if len(user) == 1:
            try:
                temp = Ordinary_User.users.get(account_number=uname, account_passWord=pwd)
                print(temp.account_number)
                id = temp.id
            except:
                return HttpResponse('密码错误')
            request.session['uid'] = id
            request.session['user_kind'] = user_kind
            return redirect('/user/index_for_user/')
        else:
            return redirect('/user/login/')

    elif user_kind == 'company_user':
        user = Company_User.comanyUsers.filter(account_number=uname)
        if len(user) == 1:
            try:
                temp = Company_User.comanyUsers.get(account_number=uname, account_passWord=pwd)
                print(temp.account_number)
                id = temp.id
            except:
                return HttpResponse('密码错误')
            request.session['uid'] = id
            request.session['user_kind'] = user_kind
            return redirect('/user/index_for_company/')
        else:
            return redirect('/user/login/')

    else:
        return HttpResponse('请输入用户种类')

def register_handel_forOrd(request):
    # 用户注册
    from hashlib import sha1
    post = request.POST
    uname = post.get('uname')
    upwd = post.get('upwd')
    cpwd = post.get('cpwd')
    mail = post.get('mail', default='123@qq.com')
    user_kind = post.get('user_kind')
    if upwd != cpwd:
        return redirect('/user/register/')
    # 加密
    s1 = sha1()
    s1.update(upwd.encode('utf-8'))
    pwd = s1.hexdigest()
    if user_kind == 'ordinary_user':
        if Ordinary_User.users.if_has(uname):
            return HttpResponse('repeated')
        o_user = Ordinary_User.users.create(uname, pwd, mail)
        return redirect('/user/login/')

def register_handel_forCom(request):
    # 公司注册
    from hashlib import sha1
    post = request.POST
    uname = post.get('uname')
    upwd = post.get('upwd')
    cpwd = post.get('cpwd')
    name = post.get('company_name')
    mail = post.get('mail', default='123@qq.com')
    user_kind = post.get('user_kind')
    company_text = post.get('company_text')
    company_num = post.get('company_num')
    price = post.get('price')
    style = post.get('style')
    images = []
    image01 = request.FILES.get('image01')
    images.append(image01)
    image02 = request.FILES.get('image02')
    images.append(image02)
    image03 = request.FILES.get('image03')
    images.append(image03)
    image04 = request.FILES.get('image04')
    images.append(image04)
    if upwd != cpwd:
        return redirect('/user/register/')
    # 加密
    s1 = sha1()
    s1.update(upwd.encode('utf-8'))
    pwd = s1.hexdigest()
    if user_kind == 'company_user':
        if Company_User.comanyUsers.if_has(uname):
            return HttpResponse('repeated')

        new_user = Company_User.comanyUsers.create(uname, pwd, name, mail, company_num, company_text, style, price)
        for image in images:
            newImage = CompanyImage(image=image, company=new_user)
            newImage.save()
        return redirect('/user/login/')
    else:
        return HttpResponse('error')


def del_session(request):
    # 清除会话的功能 登出函数
    # request.session.flush()
    del request.session['uid']
    del request.session['user_kind']
    return redirect('/user/index/')

def verifycode(request):
    # 产生验证码的函数
    from PIL import Image, ImageDraw, ImageFont
    import random
    bgcolor = (random.randrange(20, 100), random.randrange(20, 100), 255)
    width = 100
    height = 25
    im = Image.new('RGB', (width, height), bgcolor)
    draw = ImageDraw.Draw(im)
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    font = ImageFont.truetype("Dengb.ttf", 16)
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    del draw
    request.session['verifycode'] = rand_str
    from io import StringIO,BytesIO
    buf = BytesIO()
    im.save(buf, 'png')
    return HttpResponse(buf.getvalue(), 'image/png')

def aboutUs(request):

    return render(request, 'about.html')

zhuangxiusheji/zx_user/templates/gallery.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block title %}
    <title>gallery</title>
{% endblock title %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						<li><a href="{% url 'user:index' %}" >主页</a></li>
                                     <li><a href="{% url 'user:login' %}">登录</a></li>
										<li><a href="{% url 'user:select' %}">注册</a></li>
												<li><a href="{% url 'user:gallery' %}" class="active">装修案例</a></li>
							                        <li><a href="#">关于我们</a></li>
                            <!-- script for menu -->
							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>
			</div>
		</div>
{% endblock header %}
{% block body %}
	<div class="container">
	<div class="gallery">
		<h3>设计样例</h3>
		<div class="products-bottom">
			<div class="col-md-4 work-grid">
				<div id="nivo-lightbox-demo">			
					<a  href="{% static 'images/p7.jpg' %}" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
						<img src="{% static 'images/p7.jpg' %}" class="img-responsive " alt=""/>
						<div class="rotate">
							<i> </i>	
						</div>				
					 </a> 
				</div>
			</div>			
			<div class="col-md-4 work-grid">
				<div id="nivo-lightbox-demo">			
					<a  href="{% static 'images/p8.jpg' %}" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
						<img src="{% static 'images/p8.jpg' %}" class="img-responsive " alt=""/>
						<div class="rotate">
							<i> </i>	
						</div>				
					 </a> 
				</div>
			</div>
			<div class="col-md-4 work-grid">	
				<div id="nivo-lightbox-demo">			
					<a  href="{% static 'images/p9.jpg' %}" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
						<img src="{% static 'images/p9.jpg' %}" class="img-responsive " alt=""/>
						<div class="rotate">
							<i> </i>	
						</div>				
					 </a> 
				</div>	
			</div>	
			<div class="col-md-4 work-grid">
				<div id="nivo-lightbox-demo">			
					<a  href="{% static 'images/p10.jpg' %}" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
						<img src="{% static 'images/p10.jpg' %}" class="img-responsive " alt=""/>
						<div class="rotate">
							<i> </i>	
						</div>				
					 </a> 
				</div>
			</div>	
			<div class="col-md-4 work-grid">
				<div id="nivo-lightbox-demo">			
					<a  href="{% static 'images/p11.jpg' %}" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
						<img src="{% static 'images/p11.jpg' %}" class="img-responsive " alt=""/>
						<div class="rotate">
							<i> </i>	
						</div>				
					 </a> 
				</div>
			</div>	
			<div class="col-md-4 work-grid">
				<div id="nivo-lightbox-demo">			
					<a  href="{% static 'images/p12.jpg' %}" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
						<img src="{% static 'images/p12.jpg' %}" class="img-responsive " alt=""/>
						<div class="rotate">
							<i> </i>	
						</div>				
					 </a> 
				</div>
			</div>	
			<div class="col-md-4 work-grid">
				<div id="nivo-lightbox-demo">			
					<a  href="{% static 'images/p13.jpg' %}" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
						<img src="{% static 'images/p13.jpg' %}" class="img-responsive " alt=""/>
						<div class="rotate">
							<i> </i>	
						</div>				
					 </a> 
				</div>
			</div>	
			<div class="col-md-4 work-grid">
				<div id="nivo-lightbox-demo">			
					<a  href="{% static 'images/p14.jpg' %}" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
						<img src="{% static 'images/p14.jpg' %}" class="img-responsive " alt=""/>
						<div class="rotate">
							<i> </i>	
						</div>				
					 </a> 
				</div>
			</div>	
			<div class="col-md-4 work-grid">
				<div id="nivo-lightbox-demo">			
					<a  href="{% static 'images/p15.jpg' %}" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
						<img src="{% static 'images/p15.jpg' %}" class="img-responsive " alt=""/>
						<div class="rotate">
							<i> </i>	
						</div>				
					 </a> 
				</div>
			</div>				
			<div class="clearfix"> </div>	
		</div>
	</div>
	<!--script-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
			<script type="text/javascript" src="{% static 'js/nivo-lightbox.min.js'%}"></script>
				<script type="text/javascript">
				$(document).ready(function(){
				    $('#nivo-lightbox-demo a').nivoLightbox({ effect: 'fade' });
				});
				</script>

			<!---->
</div>
{% endblock body %}

zhuangxiusheji/zx_user/templates/index_for_company.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block bar %}
    <li><a href="#" class="active">主页</a></li>
    <li><a href="{% url 'user_center:show_for_company' %}">案例中心</a></li>
    <li><a href="{% url 'user_center:corporate' %}">公司资料</a></li>
    <li><a href="{% url 'draw:image' %}">在线绘图</a></li>
    <li><a href="{% url 'user:del_session' %}">退出登录</a></li>
{% endblock bar %}
{% block content %}
<div class="index-banner">
    <div class="wmuSlider example1">
        <div class="wmuSliderWrapper">
            <article style="position: absolute; width: 100%; opacity: 0;">
                <div class="banner-wrap">
                    <div class="banner_center">
                        <h1>为你提供良好的装修设计服务</h1>
                            <p>欢迎来到这里，我们拥有最优质的资源以及最自由的交流平台</p>
                    </div>
                </div>
            </article>
           <article style="position: relative; width: 100%; opacity: 1;">
                <div class="banner-wrap">
                  <div class="banner_center">
                                <h1>为你提供免费的交流平台</h1>
                                    <p>你可以自由的与别人进行交流</p>
                            </div>
                  </div>
            </article>
            <article style="position: absolute; width: 100%; opacity: 0;">
                <div class="banner-wrap">
                   <div class="banner_center">
                                <h1>为你提供专业的技术指导</h1>
                                    <p>你可以咨询专业的装修公司，与其交流</p>
                   </div>
                </div>
             </article>
             <ul class="wmuSliderPagination">
             <li><a href="#" class="">0</a></li>
             <li><a href="#" class="">1</a></li>
             <li><a href="#" class="">2</a></li>
             </ul>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery.wmuSlider.js' %}"></script>
          <script>
            $('.example1').wmuSlider();
         </script>
{% endblock content %}
{% block tail %}
        <div class="copyrights"></div>
			<div class="banner-bottom">
				<div class="container">
				<ul id="flexiselDemo3">
				 <li>
					<div class="biseller-column">
							<div class="banner-grid">
							  <img src="{% static 'images/p1.jpg' %}" class="img-responsive" alt="/">
							</div>
					</div>
				</li>
				<li>
					<div class="biseller-column">
							<div class="banner-grid">
							    <img src="{% static 'images/p2.jpg' %}" class="img-responsive" alt="/">
							</div>
						</div>
				</li>
				<li>
					<div class="biseller-column">
							<div class="banner-grid">
							<img src="{% static 'images/p3.jpg' %}" class="img-responsive" alt="/">
							</div>
					</div>
				</li>
				<li>
					<div class="biseller-column">
							<div class="banner-grid">
							 <img src="{% static 'images/p4.jpg' %}" class="img-responsive" alt="/">
						</div>
					</div>
				</li>
				<li>
					<div class="biseller-column">
							<div class="banner-grid">
							 <img src="{% static 'images/p19.jpg' %}" class="img-responsive" alt="/">
						</div>
					</div>
				</li>
	     	</ul>
		  </div>
			<script type="text/javascript">
				 $(window).load(function() {
					$("#flexiselDemo3").flexisel({
						visibleItems:3,
						animationSpeed: 1000,
						autoPlay: true,
						autoPlaySpeed: 3000,    		
						pauseOnHover: true,
						enableResponsiveBreakpoints: true,
				    	responsiveBreakpoints: { 
				    		portrait: { 
				    			changePoint:480,
				    			visibleItems:2
				    		}, 
				    		landscape: { 
				    			changePoint:640,
				    			visibleItems:2
				    		},
				    		tablet: { 
				    			changePoint:768,
				    			visibleItems:3
				    		}
				    	}
				    });
				    
				});
			   </script>
			   <script type="text/javascript" src="{% static 'js/jquery.flexisel.js' %}"></script>
				</div>
		<!-- events -->


{% endblock tail %}

zhuangxiusheji/zx_user/templates/index_for_user.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block bar %}
    <li><a href="#" class="active">主页</a></li>
    <li><a href="{% url 'user_center:show' %}">案例中心</a></li>
    <li><a href="{% url 'user_center:personal' %}">个人资料</a></li>
        <li><a href="{% url 'draw:image' %}">在线绘图</a></li>

    <li><a href="{% url 'user:del_session' %}">退出登录</a></li>
{% endblock bar %}
{% block content %}
<div class="index-banner">
    <div class="wmuSlider example1">
        <div class="wmuSliderWrapper">
            <article style="position: absolute; width: 100%; opacity: 0;">
                <div class="banner-wrap">
                    <div class="banner_center">
                        <h1>为你提供良好的装修设计服务</h1>
                            <p>欢迎来到这里，我们拥有最优质的资源以及最自由的交流平台</p>
                    </div>
                </div>
            </article>
           <article style="position: relative; width: 100%; opacity: 1;">
                <div class="banner-wrap">
                  <div class="banner_center">
                                <h1>为你提供免费的交流平台</h1>
                                    <p>你可以自由的与别人进行交流</p>
                            </div>
                  </div>
            </article>
            <article style="position: absolute; width: 100%; opacity: 0;">
                <div class="banner-wrap">
                   <div class="banner_center">
                                <h1>为你提供专业的技术指导</h1>
                                    <p>你可以咨询专业的装修公司，与其交流</p>
                   </div>
                </div>
             </article>
             <ul class="wmuSliderPagination">
             <li><a href="#" class="">0</a></li>
             <li><a href="#" class="">1</a></li>
             <li><a href="#" class="">2</a></li>
             </ul>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery.wmuSlider.js' %}"></script>
          <script>
            $('.example1').wmuSlider();
         </script>
{% endblock content %}
{% block tail %}
        <div class="copyrights"></div>
			<div class="banner-bottom">
				<div class="container">
				<ul id="flexiselDemo3">
				 <li>
					<div class="biseller-column">
							<div class="banner-grid">
							  <img src="{% static 'images/p1.jpg' %}" class="img-responsive" alt="/">
							</div>
					</div>
				</li>
				<li>
					<div class="biseller-column">
							<div class="banner-grid">
							    <img src="{% static 'images/p2.jpg' %}" class="img-responsive" alt="/">
							</div>
						</div>
				</li>
				<li>
					<div class="biseller-column">
							<div class="banner-grid">
							<img src="{% static 'images/p3.jpg' %}" class="img-responsive" alt="/">
							</div>
					</div>
				</li>
				<li>
					<div class="biseller-column">
							<div class="banner-grid">
							 <img src="{% static 'images/p4.jpg' %}" class="img-responsive" alt="/">
						</div>
					</div>
				</li>
				<li>
					<div class="biseller-column">
							<div class="banner-grid">
							 <img src="{% static 'images/p19.jpg' %}" class="img-responsive" alt="/">
						</div>
					</div>
				</li>
	     	</ul>
		  </div>
			<script type="text/javascript">
				 $(window).load(function() {
					$("#flexiselDemo3").flexisel({
						visibleItems:3,
						animationSpeed: 1000,
						autoPlay: true,
						autoPlaySpeed: 3000,    		
						pauseOnHover: true,
						enableResponsiveBreakpoints: true,
				    	responsiveBreakpoints: { 
				    		portrait: { 
				    			changePoint:480,
				    			visibleItems:2
				    		}, 
				    		landscape: { 
				    			changePoint:640,
				    			visibleItems:2
				    		},
				    		tablet: { 
				    			changePoint:768,
				    			visibleItems:3
				    		}
				    	}
				    });
				    
				});
			   </script>
			   <script type="text/javascript" src="{% static 'js/jquery.flexisel.js' %}"></script>
				</div>
		<!-- events -->


{% endblock tail %}