zhuangxiusheji/zhuangxiusheji/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from zx_user.views import index
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('zx_user.urls',namespace='user')),
    url(r'^user_center/', include('zx_user_center.urls', namespace='user_center')),
    url(r'^anli/', include('zx_anli.urls', namespace='anli')),
    url(r'^draw/', include('zx_draw.urls', namespace='draw')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zhuangxiusheji/zx_anli/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^showCompanies/$', views.show_company, name='showCompanies'),
    url(r'^show_detail/$', views.show_detail, name='show_detail'),
    url(r'^give_case/$', views.give_case, name='give_case'),
    url(r'^case_handel$', views.case_handel, name='case_handel'),
    url(r'^check_case/$', views.check_case, name='check_case'),
    url(r'^user_case/$', views.user_case, name='user_case'),
    url(r'^company_case/$', views.company_case, name='company_case'),
    url(r'^company_suggestion/$', views.company_suggestion, name='company_suggestion'),
    url(r'^suggestion_handel/$', views.suggestion_handel, name='suggestion_handel'),
    url(r'^write_comment/$', views.write_comment, name='write_comment'),
    url(r'^comment_handel/$', views.comment_handel, name='comment_handel'),
]

zhuangxiusheji/zx_draw/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^image/$', views.loadImage, name='image'),
    url(r'^upload_image/', views.upload_image, name='upload_image'),
]

zhuangxiusheji/zx_user/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^index_for_user/$', views.index_for_user, name='index_for_user'),
    url(r'^index_for_company/$', views.index_for_comapny, name='index_for_company'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^login/$', views.login, name='login'),
    url(r'^select/$', views.select_kind, name='select'),
    url(r'^kind_handel/$', views.kind_handel, name='kind_handel'),
    url(r'^register/$', views.register, name='register'),
    url(r'^longin_handel/$', views.login_handel, name='longin_handel'),
    url(r'^register_handel_forOrd/$', views.register_handel_forOrd, name='register_handel_forOrd'),
    url(r'^register_handel_forCom/$', views.register_handel_forCom, name='register_handel_forCom'),
    url(r'^del_session/$', views.del_session, name='del_session'),
    url(r'^verifycode$', views.verifycode, name='verifycode'),
    url(r'^aboutUs/$', views.aboutUs, name='aboutUs'),
]

zhuangxiusheji/zx_user_center/urls.py
from . import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^show/$', views.user_center, name='show'),
    url(r'^personal/$', views.personal, name='personal'),
    url(r'^modify_personal$', views.modify_personal, name='modify_personal'),
    url(r'^modify_personal_handel$', views.modify_personal_handel, name='modify_personal_handel'),
    url(r'^show_for_company/$', views.user_center_company, name='show_for_company'),
    url(r'^corporate/$', views.corporate, name='corporate'),
    url(r'^modify_company/$', views.modify_company, name='modify_company'),
    url(r'^modify_company_handel/$', views.modify_company_handel, name='modify_company_handel')
]

zhuangxiusheji/zx_user_center/models.py
from django.db import models

# Create your models here.

zhuangxiusheji/zx_user_center/views.py
from django.shortcuts import render,redirect
from zx_user.models import Ordinary_User, Company_User
from zx_anli.models import Anli, Comments, Suggestions
from django.http import HttpResponse
def user_center(request):
    # 用户中心的处理
    return render(request, '01.html')

def user_center_company(request):
    uid = request.session.get('uid', default=None)
    user_kind = request.session.get('user_kind', default=0)
    if user_kind == 'company_user':
        user = Company_User.comanyUsers.get(id=uid)
        context = {
            'user':user
        }
        return render(request, '02.html', context)

def personal(request):
    uid = request.session.get('uid', default=None)
    user_kind = request.session.get('user_kind', default=0)

    if user_kind == 'ordinary_user':
        # result表示查找出来的普通用户
        user = Ordinary_User.users.get(id=uid)
        cases = user.anli_set.all()
        # if len(cases) == 0:
        #     cases = '还没有提交案例'
        context = {
            'uname': user.account_number,
            'user_kind': user_kind,
            'mail':user.account_mail,
            'cases':cases,
        }
        return render(request, 'personal.html', context)

def modify_personal(request):
    uid = request.session.get('uid', default=None)
    user_kind = request.session.get('user_kind', default=0)

    if user_kind == 'ordinary_user':
        # result表示查找出来的普通用户
        user = Ordinary_User.users.get(id=uid)
        context = {
            'uname': user.account_number,
            'user_kind': user_kind,
            'mail':user.account_mail,
        }
        return render(request, 'modify_personal.html', context)

def modify_personal_handel(request):
    from hashlib import sha1
    post = request.POST
    user_kind = post.get('user_kind')
    uid = request.session.get('uid', default=None)
    if user_kind == 'ordinary_user':

        upwd = post.get('upwd')
        cpwd = post.get('cpwd')
        mail = post.get('email')
        if upwd != cpwd:
            return redirect('/user_center/modify_personal/')
        s1 = sha1()
        s1.update(upwd.encode('utf-8'))
        pwd = s1.hexdigest()
        if Ordinary_User.users.modify_password(uid, pwd, mail):
            return redirect('/user_center/personal/')

def corporate(request):
    uid = request.session.get('uid', default=None)
    user_kind = request.session.get('user_kind', default=0)

    if user_kind == 'company_user':
        user = Company_User.comanyUsers.get(id=uid)
        examime = ''.join(user.examine.split())
        if examime == 'Y':
            examime = '审核通过'
        elif examime == 'W':
            examime = '审核中'
        elif examime == 'N':
            examime = '审核不通过'
        companyImages = user.companyimage_set.all()
        context = {
            'uname': user.account_number,
            'name': user.company_name,
            'user_kind': '公司用户',
            'companyNum': user.company_num,
            'mail': user.account_mail,
            'if_passed': user.if_passed,
            'examine': examime,
            'index': user.account_describe,
            'remarks': user.casefor,
            'companyImages': user.companyimage_set.all(),
        }
        i = 1
        for image in companyImages:
            context['image'+str(i)] = image.image.url
            i += 1

        return render(request, 'corporate.html', context)

def modify_company(request):
    uid = request.session.get('uid', default=None)
    user_kind = request.session.get('user_kind', default=0)
    if user_kind == 'company_user':
        user = Company_User.comanyUsers.get(id=uid)
        examime = ''.join(user.examine.split())
        if examime == 'Y':
            examime = '审核通过'
        elif examime == 'W':
            examime = '审核中'
        elif examime == 'N':
            examime = '审核不通过'
        context = {
            'uname':user.account_number,
            'name':user.company_name, # 公司名
            'user_kind':'公司用户',
            'companyNum':user.company_num,
            'mail':user.account_mail,
            'if_passed':user.if_passed, # 是否通过
            'examine':examime, # 审核状态
            'index':user.account_describe, # 公司描述
            'remarks':user.casefor, # 备注  （不通过原因）
        }
        return render(request, 'modify_corporate.html', context)

def modify_company_handel(request):
    from hashlib import sha1
    post = request.POST
    user_kind = post.get('user_kind')
    uid = request.session.get('uid', default=None)

    if user_kind == 'company_user':
        upwd = post.get('upwd')
        cpwd = post.get('cpwd')
        mail = post.get('mail')
        name = post.get('name')
        companyNum = post.get('companyNum')
        company_text = post.get('company_text')

        if upwd != cpwd:
            return redirect('/user_center/modify_personal/')
        s1 = sha1()
        s1.update(upwd.encode('utf-8'))
        pwd = s1.hexdigest()
        canshu = {
            'account_passWord':pwd,
            'account_mail':mail,
            'company_name':name,
            'company_num':companyNum,
            'account_describe':company_text,
        }
        if Company_User.comanyUsers.modify_password(uid, canshu):
            return redirect('/user_center/corporate/')
        else:
            return HttpResponse('修改失败')

zhuangxiusheji/zx_user_center/templates/01.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block title %}
    <title>个人中心</title>
{% endblock title %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						<li><a href="{% url 'user:index_for_user' %}" >主页</a></li>
                                     <li><a href="{% url 'user_center:show' %}" class="active">案例中心</a></li>
                                                 <li><a href="{% url 'user_center:personal' %}">个人资料</a></li>
                                <li><a href="{% url 'draw:image' %}">在线绘图</a></li>
										<li><a href="{% url 'user:del_session' %}">退出登录</a></li>
{#												<li><a href="{% url 'user:gallery' %}">装修案例</a></li>#}

							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>
			</div>
		</div>
{% endblock header %}
{% block body %}
	<div class="container">
	<div class="gallery">
		<h3>案例中心</h3>
        <ul>
            <li><h2><a href="{% url 'anli:showCompanies' %}">选择公司投交案例进行咨询</a></h2></li>
            <br/>
            <li><a href="#">Choose a company to submit case</a></li>
        </ul>
        <br/><br/><br/><br/>
        <ul>
            <li><h2><a href="{% url 'anli:user_case' %}">查看用户案例</a></h2></li>
            <br/>
            <li><a href="#">View the user case</a></li>
        </ul>
        <br/><br/><br/><br/>
        <br/><br/><br/><br/>
        <div align="right">
        <p>我们拥有最优质的资源以及最自由的交流平台</p>
        </div>
	<!--script-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
			<script type="text/javascript" src="{% static 'js/nivo-lightbox.min.js'%}"></script>
				<script type="text/javascript">
				$(document).ready(function(){
				    $('#nivo-lightbox-demo a').nivoLightbox({ effect: 'fade' });
				});
				</script>

			<!---->
    </div>
</div>
{% endblock body %}

zhuangxiusheji/zx_user_center/templates/02.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block title %}
    <title>公司中心</title>
{% endblock title %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						    <li><a href="{% url 'user:index_for_company' %}" >主页</a></li>
                            <li><a href="{% url 'user_center:show_for_company' %}" class="active">案例中心</a></li>
                            <li><a href="{% url 'user_center:corporate' %}">公司资料</a></li>
                            <li><a href="{% url 'draw:image' %}">在线绘图</a></li>
                            <li><a href="{% url 'user:del_session' %}">退出登录</a></li>

							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>
			</div>
		</div>
{% endblock header %}

{% block body %}
	<div class="container">
    {% if user.if_passed == False %}
        <div class="gallery">
            <h1 style="padding: 30px;">没有通过审核哟（我们会在五个工作日内完成对您的审核）</h1>
            <h6 style="padding: 5px 50px 30px 30px;">*请通过公司资料查看审核状态</h6>
        </div>
    {% endif %}
    {% if user.if_passed == True %}
	<div class="gallery">
		<h3>案例中心</h3>
        <ul>
            <li><h2><a href="{% url 'anli:company_case' %}">我的案例</a></h2></li>
            <br/>
            <li><a href="#">Choose a company to submit case</a></li>
        </ul>
        <br/><br/><br/><br/>
        <ul>
            <li><h2><a href="{% url 'anli:company_case' %}">查看用户案例</a></h2></li>
            <br/>
            <li><a href="#">View the user case</a></li>
        </ul>
        <br/><br/><br/><br/>
        <br/><br/><br/><br/>
        <div align="right">
        <p>我们拥有最优质的资源以及最自由的交流平台</p>
        </div>
	<!--script-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
			<script type="text/javascript" src="{% static 'js/nivo-lightbox.min.js'%}"></script>
				<script type="text/javascript">
				$(document).ready(function(){
				    $('#nivo-lightbox-demo a').nivoLightbox({ effect: 'fade' });
				});
				</script>

			<!---->
    </div>
    {% endif %}
</div>
{% endblock body %}

zhuangxiusheji/zx_user_center/templates/corporate.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block title %}
    <title>公司中心</title>
{% endblock title %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						    <li><a href="{% url 'user:index_for_company' %}" >主页</a></li>
                            <li><a href="{% url 'user_center:show_for_company' %}" >案例中心</a></li>
                            <li><a href="{% url 'user_center:corporate' %}" class="active">公司资料</a></li>
                            <li><a href="{% url 'draw:image' %}">在线绘图</a></li>
                            <li><a href="{% url 'user:del_session' %}">退出登录</a></li>

							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>
			</div>
		</div>
{% endblock header %}
{% block body %}
	<div class="container">
	<div class="gallery">
		<h3>公司资料</h3>
    <div class="col-md-8 furniture" style="float: left;padding: 30px">
        <p style="font-size: larger">公司样例</p>
				<div class="furniture-girds">
					<div class="col-md-6 furniture-grid">
					<a href="#" class="mask">
					<div class="fur1">
					  <img src="{{ image1 }}" class="img-responsive zoom-img" alt="/">
						</div></a>
					<a href="#" class="mask">
					<div class="fur2">
					  <img src="{{ image2 }}" class="img-responsive zoom-img" alt="/">
						</div></a>
				</div>
				<div class="col-md-6 furniture-grid">
				<a href="#" class="mask">
					<div class="fur1">
					  <img src="{{ image3 }}" class="img-responsive zoom-img" alt="/">
						</div></a>
					<a href="#" class="mask">
					<div class="fur2">
					  <img src="{{ image4 }}" class="img-responsive zoom-img" alt="/">
						</div></a>
				</div>
					<div class="clearfix"></div>
			</div>
    </div>
    <div style="clear: both">
    <ul>
        <li><h4>用户名：{{ uname }}</h4></li>
        <br/><br/><br/>
        <li><h4>用户种类：公司用户</h4></li>
        <br/><br/><br/>
        <li><h4>营业执照号码：{{ companyNum }}</h4></li>
        <br/><br/><br/>
        <li><h4>公司名称：{{ name }}</h4></li>
        <br/><br/><br/>
        <li><h4>邮箱：{{ mail }}</h4></li>
        <br/><br/><br/>
        <li><h4>审核状态:<a style="color: red"> {{ examine }}</a></h4></li>
        <br/><br/><br/>
        <li><h4>公司描述:</h4>
            <br/>
            <textarea style="padding: 10px;" rows="10" cols="60" readonly="readonly">{{ index }}</textarea></li>
        {% if if_passed == False and examine == '审核不通过'%}
            {# 如果审核不通过显示不通过原因 #}
            <br/><br/><br/>
            <li><h4>不通过原因:</h4>
            <br/>
            <textarea style="padding: 10px;" rows="10" cols="60" readonly="readonly">{{ remarks }}</textarea></li>
        {% endif %}
        <div  style="padding: 15px">
            <form action="{% url 'user_center:modify_company' %}">
                <button type="submit" >修改公司资料</button>
            </form>
        </div>
                    <p style="font-size: 13px;position: relative">*点击该按钮后会进入修改资料页面，修改后审核状态会变为审核中。</p>

    </ul></div>

	<!--script-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
			<script type="text/javascript" src="{% static 'js/nivo-lightbox.min.js'%}"></script>
				<script type="text/javascript">
				$(document).ready(function(){
				    $('#nivo-lightbox-demo a').nivoLightbox({ effect: 'fade' });
				});
				</script>

			<!---->
    </div>

</div>
{% endblock body %}

zhuangxiusheji/zx_user_center/templates/modify_corporate.html
<!DOCTYPE html>
{% load staticfiles %}
{# 注册页面 #}
<html lang="en" class="no-js">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>修改信息</title>
{#    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" />#}
<link rel="stylesheet" type="text/css" href="{% static 'login/css/normalize.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'login/css/demo.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'login/css/component.css' %}" />
<!--[if IE]>
	<script src="js/html5.js"></script>
<![endif]-->
       <style type="text/css">
             {#body{font-size:12px;}#}
             p,div{margin:0;padding:0}
             .textarea{

                 width:350px;
                 height:100px;
                 position:absolute;
                 border-radius:10px;
                 background-color:#222;
                 color:white;
                 resize:none;
                 border: 2px solid #009688;
                 z-index:9
            }
             .note{
             position:absolute;line-height:20px;padding:3px 5px;
             }
        </style>
</head>
<body>
		<div class="container demo-1">
			<div class="content">
				<div id="large-header" class="large-header">
					<canvas id="demo-canvas"></canvas>
					<div class="logo_box">
						<h3>修改信息</h3>
						<form method="post" action="{% url 'user_center:modify_company_handel' %}">
                            {% csrf_token %}
                            <input type="hidden" name="user_kind" value="company_user">
							<div class="input_outer">
								<span class="u_user"></span>
								<div style="padding:15px 20px 15px 80px ;">用户名：{{ uname }}</div>
							</div>
                            <div class="input_outer">
						        <span class="u_user"></span>
                                <input id="n1" name="name" class="text"   type="text" placeholder="请输入新公司名,不填则不修改">
							</div>
                            <div class="input_outer">
                                <span class="us_uer"></span>
                                <input id="n1" name="companyNum" class="text"   type="text" placeholder="请输入新执照号码,不填则不修改">

							</div>
                            <div class="input_outer">
								<span class="u_user"></span>
								<input id="n1" name="mail" class="text"   type="text" placeholder="请输入新邮箱，不填则不修改">

							</div>
							<div class="input_outer">
								<span class="us_uer"></span>
								<input id="n2" name="upwd" class="text"   value="" type="password" placeholder="请输入新密码">

							</div>
							<div class="input_outer">
								<span class="us_uer"></span>
								<input id="n3" name="cpwd" class="text"  value="" type="password" placeholder="请再次输入新密码">

							</div>
                            <div class="input_outer_text">
                                     <p style="font-size: 13px">*在这里写入你们公司新的简介，将作为审核的依据</p>
                                    <textarea   name="company_text" rows="50" cols="100"  class="textarea" >{{ index }}</textarea>
							</div>

							<div class="input_outer">
								<span class="uss_uer"><img src="{% url 'user:verifycode' %}"></span>
                                <input class="text" type="text" value="" name="imgCode" placeholder="请输入验证码">
								<span class="error">验证码错误!</span>
                            </div>
                            <div class="mb2">
								<a class="act-but submit" href="javascript:;" style="color: #FFFFFF">
								<input type="submit" value="确定" />
								</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

		<script src="{% static 'login/js/TweenLite.min.js' %}"></script>
		<script src="{% static 'login/js/jquery.min.js' %}"></script>
		<script src="{% static 'login/js/EasePack.min.js' %}"></script>
		<script src="{% static 'login/js/rAF.js' %}"></script>
		<script src="{% static 'login/js/demo-1.js' %}"></script>
{#		<script src="{% static 'login/js/check.js' %}"></script>#}
		<div style="text-align:center;">
		</div>
	</body>
</html>

zhuangxiusheji/zx_user_center/templates/modify_personal.html
<!DOCTYPE html>
{% load staticfiles %}
{# 注册页面 #}
<html lang="en" class="no-js">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>修改信息</title>
<link rel="stylesheet" type="text/css" href="{% static 'login/css/normalize.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'login/css/demo.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'login/css/component.css' %}" />
<!--[if IE]>
	<script src="js/html5.js"></script>
<![endif]-->
</head>
<body>
		<div class="container demo-1">
			<div class="content">
				<div id="large-header" class="large-header">
					<canvas id="demo-canvas"></canvas>
					<div class="logo_box">
						<h3>修改信息</h3>
						<form method="post" action="{% url 'user_center:modify_personal_handel' %}">
                            {% csrf_token %}
                            <input type="hidden" name="user_kind" value="ordinary_user">
							<div class="input_outer">
								<span class="u_user"></span>
								<div style="padding:15px 20px 15px 80px ;">用户名：{{ uname }}</div>
							</div>
                            <div class="input_outer">
								<span class="u_user"></span>
								<input id="n1" name="email" class="text"   type="text" placeholder="请输入新邮箱，不填则不修改">
								<span class="error">用户名的长度至少6位!</span>
							</div>
							<div class="input_outer">
								<span class="us_uer"></span>
								<input id="n2" name="upwd" class="text"   value="" type="password" placeholder="请输入新密码">
								<span class="error">密码的长度至少6位!</span>
							</div>
							<div class="input_outer">
								<span class="us_uer"></span>
								<input id="n3" name="cpwd" class="text"  value="" type="password" placeholder="请再次输入新密码">
								<span class="error">两次输入密码不一致!</span>
							</div>
							<div class="input_outer">
								<span class="uss_uer"><img src="{% url 'user:verifycode' %}"></span>
                                <input class="text" type="text" value="" name="imgCode" placeholder="请输入验证码">
								<span class="error">验证码错误!</span>
                            </div>
							<h5 style="padding-left:62px;">我已阅读并同意<a href="#" target="_blank" style="color:#0096e6;">《用户协议》</a></h5>
							<div class="mb2">
								<a class="act-but submit" href="javascript:;" style="color: #FFFFFF">
								<input type="submit" value="确定" />
								</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

		<script src="{% static 'login/js/TweenLite.min.js' %}"></script>
		<script src="{% static 'login/js/jquery.min.js' %}"></script>
		<script src="{% static 'login/js/EasePack.min.js' %}"></script>
		<script src="{% static 'login/js/rAF.js' %}"></script>
		<script src="{% static 'login/js/demo-1.js' %}"></script>
{#		<script src="{% static 'login/js/check.js' %}"></script>#}
		<div style="text-align:center;">
		</div>
	</body>
</html>

zhuangxiusheji/zx_user_center/templates/personal.html
{% extends 'base/Base.html' %}
{% load staticfiles %}
{% block title %}
    <title>个人中心</title>
{% endblock title %}
{% block header %}
    	<div class="header head-top">
			<div class="container">
				<div class="header-top">
					<div class="logo">
						<a href="{% url 'user:index' %}">装修设计<span>网站</span></a>
					</div>
						<div class="social-icons">
							<a href="#"><i class="icon1"></i></a>
								<a href="#"><i class="icon2"></i></a>
										<a href="#"><i class="icon3"></i></a>
												<a href="#"><i class="icon4"></i></a>
						</div>
							<div class="clearfix"></div>
				</div>
				<div class="top-menu">
					<span class="menu"><img src="{% static 'images/menu.png' %}" alt=""/>  </span>
						<ul>
						    <li><a href="{% url 'user:index_for_user' %}" >主页</a></li>
                            <li><a href="{% url 'user_center:show' %}" >案例中心</a></li>
                            <li><a href="{% url 'user_center:personal' %}" class="active">个人资料</a></li>
							<li><a href="{% url 'draw:image' %}">在线绘图</a></li>
                            <li><a href="{% url 'user:del_session' %}">退出登录</a></li>

                            {#												<li><a href="{% url 'user:gallery' %}">装修案例</a></li>#}

							<script>
							 $("span.menu").click(function(){
							 $(".top-menu ul").slideToggle("slow" , function(){
							 });
							 });
							 </script>
							<!-- //script for menu -->

												<div class="clearfix"></div>
					</ul>
				</div>
			</div>
		</div>
{% endblock header %}
{% block body %}
	<div class="container">
	<div class="gallery">
		<h3>个人资料</h3>
    <ul>
        <li><h4>用户名：{{ uname }}</h4></li>
        <br/><br/><br/>
        <li><h4>用户种类：普通用户</h4></li>
        <br/><br/><br/>
        <li><h4>邮箱：{{ mail }}</h4></li>
        <br/><br/><br/>
        <li>
            <h4>提交过的案例:</h4>
            <ul>
                <br/>

                {% for case in cases %}
                <li><a href="{% url 'anli:check_case' %}?cid={{ case.id }}">&nbsp;&nbsp;&nbsp;&nbsp;{{ case.anli_name }}</a></li>
                {% endfor %}
            </ul>
        </li>
        <div align="center">
            <form action="{% url 'user_center:modify_personal' %}">
        <button type="submit" >修改个人资料</button>
                </form>
        </div>
    </ul>
	<!--script-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
			<script type="text/javascript" src="{% static 'js/nivo-lightbox.min.js'%}"></script>
				<script type="text/javascript">
				$(document).ready(function(){
				    $('#nivo-lightbox-demo a').nivoLightbox({ effect: 'fade' });
				});
				</script>

			<!---->
    </div>
</div>
{% endblock body %}